<?php
/**
 * User:  zxwtry
 * File:  Student.php
 * Date:  2017/11/19
 * Time:  8:58
 */


namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model {
    //默认 students
    //指定表明
    protected $table = 'student';

    //默认以id作为主键
    //指定id
    protected $primaryKey = 'id';

    //指定允许批量赋值的字段
    protected $fillable = ['name', 'age'];

    //设定某个字段，不允许批量赋值
    protected $guarded = [];


    //关闭自动添加
    //created_at字段
    //updated_at字段
    //默认打开
    //自动维护时间戳
    public $timestamps = true;

    //修改时间格式
    protected function getDateFormat()
    {
        //return parent::getDateFormat(); // TODO: Change the autogenerated stub
        return time();
        //time()返回的是：UNIX时间戳
    }

    protected function asDateTime($value)
    {
        //return parent::asDateTime($value); // TODO: Change the autogenerated stub
        return $value;
    }


}